version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bike_service_db
    environment:
      POSTGRES_USER: bike_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bike_user -d bike_service" ]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build:
      context: .
    container_name: bike_service_api
    environment:
      DATABASE_URL: postgresql://bike_user:password@db/bike_service
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
